packages:
  # Next.js test fixture projects
  - tests/default
  - tests/standalone
  - tests/export

catalog:
  "@types/node": ^22
  typescript: ^5
  next: ^16
  eslint-config-next: ^16
  react: ^19
  react-dom: ^19
  "@types/react": ^19
  "@types/react-dom": ^19
